name: binary_map_file
description: "Performant key-value file based serialization. Pure Dart, secured support"
version: 1.7.0
homepage: https://github.com/annotium/binary_map_file

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  path: ^1.9.0
  path_provider: ^2.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
